# coding: utf-8

"""
    Overseerr API

    This is the documentation for the Overseerr API backend.  Two primary authentication methods are supported:  - **Cookie Authentication**: A valid sign-in to the `/auth/plex` or `/auth/local` will generate a valid authentication cookie. - **API Key Authentication**: Sign-in is also possible by passing an `X-Api-Key` header along with a valid API Key generated by Overseerr.   # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import annotations
from inspect import getfullargspec
import pprint
import re  # noqa: F401
import json


from typing import Any, Dict, Optional, Union
from pydantic import BaseModel

class Episode(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    id: Optional[float]
    name: Optional[str]
    air_date: Optional[str]
    episode_number: Optional[float]
    overview: Optional[str]
    production_code: Optional[str]
    season_number: Optional[float]
    show_id: Optional[float]
    still_path: Optional[str]
    vote_average: Optional[float]
    vote_count: Optional[float]
    additional_properties: Dict[str, Any] = {}
    __properties = ["id", "name", "airDate", "episodeNumber", "overview", "productionCode", "seasonNumber", "showId", "stillPath", "voteAverage", "voteCount"]

    class Config:
        allow_population_by_field_name = True
        validate_assignment = True
        alias_generator = lambda x: x.split("_")[0] + "".join(word.capitalize() for word in x.split("_")[1:])

    def __getitem__(self, item):
        return getattr(self, item)

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Episode:
        """Create an instance of Episode from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                            "additional_properties"
                          },
                          exclude_none=True)
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if air_date (nullable) is None
        if self.air_date is None:
            _dict['airDate'] = None

        # set to None if still_path (nullable) is None
        if self.still_path is None:
            _dict['stillPath'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> Episode:
        """Create an instance of Episode from a dict"""
        if obj is None:
            return None

        if type(obj) is not dict:
            return Episode.parse_obj(obj)

        _obj = Episode.parse_obj({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "air_date": obj.get("airDate"),
            "episode_number": obj.get("episodeNumber"),
            "overview": obj.get("overview"),
            "production_code": obj.get("productionCode"),
            "season_number": obj.get("seasonNumber"),
            "show_id": obj.get("showId"),
            "still_path": obj.get("stillPath"),
            "vote_average": obj.get("voteAverage"),
            "vote_count": obj.get("voteCount")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj

