# coding: utf-8

"""
    Overseerr API

    This is the documentation for the Overseerr API backend.  Two primary authentication methods are supported:  - **Cookie Authentication**: A valid sign-in to the `/auth/plex` or `/auth/local` will generate a valid authentication cookie. - **API Key Authentication**: Sign-in is also possible by passing an `X-Api-Key` header along with a valid API Key generated by Overseerr.   # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import annotations
from inspect import getfullargspec
import pprint
import re  # noqa: F401
import json


from typing import Any, Dict, List, Optional, Union
from pydantic import BaseModel
from overseerr.models.credit_cast import CreditCast
from overseerr.models.credit_crew import CreditCrew

class GetPersonCombinedCredits200Response(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    cast: Optional[List]
    crew: Optional[List]
    id: Optional[float]
    additional_properties: Dict[str, Any] = {}
    __properties = ["cast", "crew", "id"]

    class Config:
        allow_population_by_field_name = True
        validate_assignment = True
        alias_generator = lambda x: x.split("_")[0] + "".join(word.capitalize() for word in x.split("_")[1:])

    def __getitem__(self, item):
        return getattr(self, item)

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> GetPersonCombinedCredits200Response:
        """Create an instance of GetPersonCombinedCredits200Response from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                            "additional_properties"
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of each item in cast (list)
        _items = []
        if self.cast:
            for _item in self.cast:
                if _item:
                    _items.append(_item.to_dict())
            _dict['cast'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in crew (list)
        _items = []
        if self.crew:
            for _item in self.crew:
                if _item:
                    _items.append(_item.to_dict())
            _dict['crew'] = _items
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> GetPersonCombinedCredits200Response:
        """Create an instance of GetPersonCombinedCredits200Response from a dict"""
        if obj is None:
            return None

        if type(obj) is not dict:
            return GetPersonCombinedCredits200Response.parse_obj(obj)

        _obj = GetPersonCombinedCredits200Response.parse_obj({
            "cast": [CreditCast.from_dict(_item) for _item in obj.get("cast")] if obj.get("cast") is not None else None,
            "crew": [CreditCrew.from_dict(_item) for _item in obj.get("crew")] if obj.get("crew") is not None else None,
            "id": obj.get("id")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj

