# coding: utf-8

"""
    Overseerr API

    This is the documentation for the Overseerr API backend.  Two primary authentication methods are supported:  - **Cookie Authentication**: A valid sign-in to the `/auth/plex` or `/auth/local` will generate a valid authentication cookie. - **API Key Authentication**: Sign-in is also possible by passing an `X-Api-Key` header along with a valid API Key generated by Overseerr.   # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import annotations
from inspect import getfullargspec
import pprint
import re  # noqa: F401
import json



from pydantic import BaseModel

class MainSettings(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    api_key: Optional[str]
    app_language: Optional[str]
    application_title: Optional[str]
    application_url: Optional[str]
    trust_proxy: Optional[bool]
    csrf_protection: Optional[bool]
    hide_available: Optional[bool]
    partial_requests_enabled: Optional[bool]
    local_login: Optional[bool]
    new_plex_login: Optional[bool]
    default_permissions: Optional[float]
    additional_properties: Dict[str, Any] = {}
    __properties = ["apiKey", "appLanguage", "applicationTitle", "applicationUrl", "trustProxy", "csrfProtection", "hideAvailable", "partialRequestsEnabled", "localLogin", "newPlexLogin", "defaultPermissions"]

    class Config:
        allow_population_by_field_name = True
        validate_assignment = True
        alias_generator = lambda x: x.split("_")[0] + "".join(word.capitalize() for word in x.split("_")[1:])

    def __getitem__(self, item):
        return getattr(self, item)

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> MainSettings:
        """Create an instance of MainSettings from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                            "api_key",
                            "additional_properties"
                          },
                          exclude_none=True)
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> MainSettings:
        """Create an instance of MainSettings from a dict"""
        if obj is None:
            return None

        if type(obj) is not dict:
            return MainSettings.parse_obj(obj)

        _obj = MainSettings.parse_obj({
            "api_key": obj.get("apiKey"),
            "app_language": obj.get("appLanguage"),
            "application_title": obj.get("applicationTitle"),
            "application_url": obj.get("applicationUrl"),
            "trust_proxy": obj.get("trustProxy"),
            "csrf_protection": obj.get("csrfProtection"),
            "hide_available": obj.get("hideAvailable"),
            "partial_requests_enabled": obj.get("partialRequestsEnabled"),
            "local_login": obj.get("localLogin"),
            "new_plex_login": obj.get("newPlexLogin"),
            "default_permissions": obj.get("defaultPermissions")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj

