# coding: utf-8

"""
    Overseerr API

    This is the documentation for the Overseerr API backend.  Two primary authentication methods are supported:  - **Cookie Authentication**: A valid sign-in to the `/auth/plex` or `/auth/local` will generate a valid authentication cookie. - **API Key Authentication**: Sign-in is also possible by passing an `X-Api-Key` header along with a valid API Key generated by Overseerr.   # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import annotations
from inspect import getfullargspec
import pprint
import re  # noqa: F401
import json



from pydantic import BaseModel

class MediaInfo(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    id: Optional[float]
    tmdb_id: Optional[float]
    tvdb_id: Optional[float]
    status: Optional[float]
    requests: Optional[List]
    created_at: Optional[str]
    updated_at: Optional[str]
    additional_properties: Dict[str, Any] = {}
    __properties = ["id", "tmdbId", "tvdbId", "status", "requests", "createdAt", "updatedAt"]

    class Config:
        allow_population_by_field_name = True
        validate_assignment = True
        alias_generator = lambda x: x.split("_")[0] + "".join(word.capitalize() for word in x.split("_")[1:])

    def __getitem__(self, item):
        return getattr(self, item)

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> MediaInfo:
        """Create an instance of MediaInfo from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                            "id",
                            "tmdb_id",
                            "tvdb_id",
                            "requests",
                            "created_at",
                            "updated_at",
                            "additional_properties"
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of each item in requests (list)
        _items = []
        if self.requests:
            for _item in self.requests:
                if _item:
                    _items.append(_item.to_dict())
            _dict['requests'] = _items
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if tvdb_id (nullable) is None
        if self.tvdb_id is None:
            _dict['tvdbId'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> MediaInfo:
        """Create an instance of MediaInfo from a dict"""
        if obj is None:
            return None

        if type(obj) is not dict:
            return MediaInfo.parse_obj(obj)

        _obj = MediaInfo.parse_obj({
            "id": obj.get("id"),
            "tmdb_id": obj.get("tmdbId"),
            "tvdb_id": obj.get("tvdbId"),
            "status": obj.get("status"),
            "requests": [MediaRequest.from_dict(_item) for _item in obj.get("requests")] if obj.get("requests") is not None else None,
            "created_at": obj.get("createdAt"),
            "updated_at": obj.get("updatedAt")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj

