# coding: utf-8

"""
    Overseerr API

    This is the documentation for the Overseerr API backend.  Two primary authentication methods are supported:  - **Cookie Authentication**: A valid sign-in to the `/auth/plex` or `/auth/local` will generate a valid authentication cookie. - **API Key Authentication**: Sign-in is also possible by passing an `X-Api-Key` header along with a valid API Key generated by Overseerr.   # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import annotations
from inspect import getfullargspec
import pprint
import re  # noqa: F401
import json


from typing import Any, ClassVar, Dict, List, Optional, Union
from pydantic import BaseModel

class User(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    id: Optional[int]
    email: Optional[str]
    username: Optional[str]
    plex_token: Optional[str]
    plex_username: Optional[str]
    user_type: Optional[int]
    permissions: Optional[float]
    avatar: Optional[str]
    created_at: Optional[str]
    updated_at: Optional[str]
    request_count: Optional[float]
    additional_properties: Dict[str, Any] = {}
    __properties = ["id", "email", "username", "plexToken", "plexUsername", "userType", "permissions", "avatar", "createdAt", "updatedAt", "requestCount"]

    class Config:
        allow_population_by_field_name = True
        validate_assignment = True
        alias_generator = lambda x: x.split("_")[0] + "".join(word.capitalize() for word in x.split("_")[1:])

    def __getitem__(self, item):
        return getattr(self, item)

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> User:
        """Create an instance of User from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                            "id",
                            "email",
                            "plex_token",
                            "plex_username",
                            "user_type",
                            "avatar",
                            "created_at",
                            "updated_at",
                            "request_count",
                            "additional_properties"
                          },
                          exclude_none=True)
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> User:
        """Create an instance of User from a dict"""
        if obj is None:
            return None

        if type(obj) is not dict:
            return User.parse_obj(obj)

        _obj = User.parse_obj({
            "id": obj.get("id"),
            "email": obj.get("email"),
            "username": obj.get("username"),
            "plex_token": obj.get("plexToken"),
            "plex_username": obj.get("plexUsername"),
            "user_type": obj.get("userType"),
            "permissions": obj.get("permissions"),
            "avatar": obj.get("avatar"),
            "created_at": obj.get("createdAt"),
            "updated_at": obj.get("updatedAt"),
            "request_count": obj.get("requestCount")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj

